// <auto-generated />
using ENGHelperBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ENGHelperBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250414131358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ENGHelperBot.Data.Entities.Dictionary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("dictionaries");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.DictionaryWord", b =>
                {
                    b.Property<long>("DictionaryId")
                        .HasColumnType("bigint")
                        .HasColumnName("dictionary_id")
                        .HasColumnOrder(1);

                    b.Property<long>("WordId")
                        .HasColumnType("bigint")
                        .HasColumnName("word_id")
                        .HasColumnOrder(2);

                    b.HasKey("DictionaryId", "WordId");

                    b.HasIndex("WordId");

                    b.ToTable("dictionaries_words");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.Example", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("translation");

                    b.Property<long>("WordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("examples");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.Phrase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("translation");

                    b.Property<long>("WordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("phrases");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.Translation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.ToTable("translation");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("text");

                    b.Property<string>("Transcription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transcription");

                    b.HasKey("Id");

                    b.ToTable("words");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.WordTranslation", b =>
                {
                    b.Property<long>("WordId")
                        .HasColumnType("bigint")
                        .HasColumnName("word_id")
                        .HasColumnOrder(1);

                    b.Property<long>("TranslationId")
                        .HasColumnType("bigint")
                        .HasColumnName("translation_id")
                        .HasColumnOrder(2);

                    b.HasKey("WordId", "TranslationId");

                    b.HasIndex("TranslationId");

                    b.ToTable("words_translations");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.Dictionary", b =>
                {
                    b.HasOne("ENGHelperBot.Data.Entities.User", "User")
                        .WithMany("Dictionaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.DictionaryWord", b =>
                {
                    b.HasOne("ENGHelperBot.Data.Entities.Dictionary", "Dictionary")
                        .WithMany()
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENGHelperBot.Data.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.WordTranslation", b =>
                {
                    b.HasOne("ENGHelperBot.Data.Entities.Translation", "Translation")
                        .WithMany("WordTranslations")
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENGHelperBot.Data.Entities.Word", "Word")
                        .WithMany("WordTranslations")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Translation");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.Translation", b =>
                {
                    b.Navigation("WordTranslations");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.User", b =>
                {
                    b.Navigation("Dictionaries");
                });

            modelBuilder.Entity("ENGHelperBot.Data.Entities.Word", b =>
                {
                    b.Navigation("WordTranslations");
                });
#pragma warning restore 612, 618
        }
    }
}
